import os
import sys
import json
import shutil
import urllib.request
import urllib.error
import zipfile
import re

# --- CONFIGURATION ---
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS_DIR = os.path.join(PROJECT_ROOT, "static", "lib", "fonts")
CSS_DIR = os.path.join(PROJECT_ROOT, "static", "css")
CSS_FILE = os.path.join(CSS_DIR, "fonts.css")

def print_status(msg, status="INFO"):
    colors = {"INFO": "\033[94m", "SUCCESS": "\033[92m", "WARN": "\033[93m", "ERROR": "\033[91m", "RESET": "\033[0m"}
    print(f"{colors.get(status, '')}[{status}] {msg}{colors['RESET']}")

def verify_idempotency():
    """Checks if the exact required font assets and manifest already exist."""
    inter_exists = os.path.exists(os.path.join(FONTS_DIR, "Inter-Variable.woff2"))
    jb_exists = os.path.exists(os.path.join(FONTS_DIR, "JetBrainsMono-Variable.woff2"))
    css_exists = os.path.exists(CSS_FILE)
    return inter_exists and jb_exists and css_exists

# --- STRATEGY 1: GITHUB RELEASE HUNTER (Best for Inter) ---
def fetch_from_github(name, repo, keywords):
    print_status(f"Querying GitHub for {name} ({repo})...", "INFO")
    api_url = f"https://api.github.com/repos/{repo}/releases/latest"
    
    try:
        req = urllib.request.Request(api_url, headers={"User-Agent": "RLM-Hydrator"})
        with urllib.request.urlopen(req, timeout=15) as r:
            data = json.loads(r.read().decode())
            
        # Find Asset
        asset = next((a for a in data.get('assets', []) if a['name'].endswith('.zip')), None)
        if not asset: return None

        # Download Zip
        zip_path = os.path.join(FONTS_DIR, "temp_font.zip")
        with urllib.request.urlopen(asset['browser_download_url'], timeout=30) as response, open(zip_path, 'wb') as out:
            shutil.copyfileobj(response, out)

        # Hunt for WOFF2
        extracted_name = None
        with zipfile.ZipFile(zip_path, 'r') as z:
            # Prioritize matches
            candidates = [f for f in z.namelist() if not "__macosx" in f.lower()]
            target = next((f for f in candidates if all(k in f.lower() for k in keywords)), None)
            
            if target:
                final_name = f"{name}-Variable.woff2"
                with z.open(target) as source, open(os.path.join(FONTS_DIR, final_name), 'wb') as dest:
                    shutil.copyfileobj(source, dest)
                extracted_name = final_name
                print_status(f"   -> Extracted: {final_name}", "SUCCESS")
            else:
                print_status(f"   -> No matching WOFF2 found in zip.", "WARN")

        try: os.remove(zip_path)
        except: pass
        return extracted_name

    except Exception as e:
        print_status(f"GitHub Error: {e}", "ERROR")
        return None

# --- STRATEGY 2: GOOGLE FONTS INTERCEPTOR (Best for JetBrains Mono) ---
def fetch_from_google_fonts(name, family_param):
    print_status(f"Intercepting Google Fonts for {name}...", "INFO")
    
    # We ask for the Variable Weight version (100..800)
    css_url = f"https://fonts.googleapis.com/css2?family={family_param}&display=swap"
    
    try:
        # User-Agent is CRITICAL. If we don't send a modern agent, Google sends TTF.
        headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"}
        req = urllib.request.Request(css_url, headers=headers)
        
        with urllib.request.urlopen(req, timeout=10) as r:
            css_content = r.read().decode()

        # Regex to find the "Latin" subset URL
        urls = re.findall(r'src:\s*url\((https://[^\)]+\.woff2)\)', css_content)
        
        if not urls:
            print_status("   -> Could not parse WOFF2 URL from CSS.", "ERROR")
            return None
            
        # Download the Latin subset (usually the last one listed)
        target_url = urls[-1] 
        final_name = f"{name}-Variable.woff2"
        
        with urllib.request.urlopen(target_url, timeout=30) as response, open(os.path.join(FONTS_DIR, final_name), 'wb') as out:
            shutil.copyfileobj(response, out)
            
        print_status(f"   -> Downloaded: {final_name}", "SUCCESS")
        return final_name

    except Exception as e:
        print_status(f"Google Fonts Error: {e}", "ERROR")
        return None

def generate_css(fonts):
    print_status("Generating CSS Manifest...", "INFO")
    css = "/* RLM TITAN TYPOGRAPHY MANIFEST */\n/* Generated by tools/setup_fonts.py */\n\n"
    
    if fonts.get('Inter'):
        css += """@font-face {
    font-family: 'Inter';
    src: url('../lib/fonts/Inter-Variable.woff2') format('woff2-variations');
    font-weight: 100 900;
    font-style: normal;
    font-display: swap;
}\n\n"""

    if fonts.get('JetBrainsMono'):
        css += """@font-face {
    font-family: 'JetBrains Mono';
    src: url('../lib/fonts/JetBrainsMono-Variable.woff2') format('woff2-variations');
    font-weight: 100 800;
    font-style: normal;
    font-display: swap;
}\n"""

    with open(CSS_FILE, 'w') as f:
        f.write(css)
    print_status(f"Manifest written to: {CSS_FILE}", "SUCCESS")

def main():
    print("="*60)
    print("      RLM TYPOGRAPHY HYDRATION PROTOCOL v2.0     ")
    print("="*60)
    
    if verify_idempotency():
        print_status("Typography Subsystem already hydrated. Bypassing execution.", "SUCCESS")
        sys.exit(0)
    
    if not os.path.exists(FONTS_DIR): os.makedirs(FONTS_DIR)
    if not os.path.exists(CSS_DIR): os.makedirs(CSS_DIR)
    
    installed = {}
    
    installed['Inter'] = fetch_from_github(
        "Inter", 
        "rsms/inter", 
        ["inter", "variable", "woff2"]
    )
    
    installed['JetBrainsMono'] = fetch_from_google_fonts(
        "JetBrainsMono", 
        "JetBrains+Mono:wght@100..800"
    )
    
    generate_css(installed)
    
    if all(installed.values()):
        print_status("Typography Subsystem Online (WOFF2 Optimized).", "SUCCESS")
    else:
        print_status("Typography Hydration Partial.", "WARN")

if __name__ == "__main__":
    main()